[build-system]
requires = ["setuptools >= 70.0"]
build-backend = "setuptools.build_meta"

[project]
name = "constrainthg"
version = "0.2.4"
dependencies = [
    "numpy"
]
requires-python = ">=3.1"
authors = [
  {name = "John Morris", email = "constrainthg@gmail.com"},
]
description = "Kernel for building and simulating constraint hypergraphs."
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICENSE*"]
keywords = ["hypergraphs", "systems engineering", "modeling", "simulation"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Programming Language :: Python"
]

[project.urls]
homepage = "https://constrainthg.readthedocs.io/en/latest/"
documentation = "https://constrainthg.readthedocs.io/en/latest/api/index.html"
repository = "https://github.com/jmorris335/ConstraintHg"
issues = "https://github.com/jmorris335/ConstraintHg/issues"

[project.scripts]
constrainthg-cli = "constrainthg:main_cli"

[tool.pytest.ini_options]
pythonpath = "src"
addopts = [
    "--import-mode=importlib",
]